# -*- coding: utf-8 -*-
"""DataCleaningAssignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ufbxWhWC-wIEREmD9pKzKG-lNKR7hXfv

### Q1. Missing Data Identification — Scenario: The hospital suspects incomplete patient records. Task: Identify missing values in each column. Calculate percentage of missing data.

-->  

Answer:  
Out of 5,100 total records, two columns contain missing values: Age, with 600 missing entries (11.76%), and Treatment_Cost, with 593 missing entries (11.63%). All other columns — Patient_ID, Gender, City, Diagnosis, Hospital_Visits, Insurance_Coverage, and Admission_Date — have zero missing values.

This confirms the hospital's suspicion that records are incomplete, specifically concentrated in two critical numeric fields. Since Age and Treatment_Cost are both important for medical and financial analysis, these missing values must be addressed before any further analysis is performed.

```python
import pandas as pd

df = pd.read_csv('healthcare_data_cleaning_dataset.csv')

missing_count = df.isnull().sum()
print("Missing Values Count:\n", missing_count)

missing_percent = (df.isnull().sum() / len(df)) * 100
print("\nMissing Values Percentage:\n", missing_percent.round(2))
```

---
---

### Q2. Handling Missing Age — Scenario: Age is critical for medical analysis, but some values are missing. Task: Replace missing Age values with an appropriate method. Justify your choice (mean/median).

-->  

Answer:  
The Age column has a skewness of approximately -0.01, which is very close to zero, indicating a nearly symmetric distribution (mean ≈ 49.6, median = 50). Since there is no significant skew or extreme outliers pulling the distribution in one direction, both mean and median would technically produce similar results here.

However, median is chosen as the imputation method because it is the safer, standard practice for Age in healthcare datasets. It is robust to any outliers that might still be present, and it returns a realistic whole-number value rather than a decimal average like 49.6, which doesn't make practical sense for a person's age.

```python
print("Age Skewness:", df['Age'].skew())

median_age = df['Age'].median()
df['Age'] = df['Age'].fillna(median_age)

print("Missing values in Age after imputation:", df['Age'].isnull().sum())
```

---
---

### Q3. Handling Missing Treatment Cost — Scenario: Treatment cost is highly skewed due to expensive treatments. Task: Handle missing Treatment_Cost values. Choose the correct imputation method and explain why.

-->  

Answer:  
The Treatment_Cost column has a skewness of approximately 4.49, which indicates strong right-skewness. This happens because a small number of very expensive treatments pull the mean (≈ ₹26,920) noticeably higher than the median (≈ ₹24,797).

Because of this skew, using the mean for imputation would be misleading, as it is inflated by costly outlier cases and doesn't represent a "typical" patient's cost. The median is the correct choice here since it represents the central tendency more accurately without being distorted by extreme values.

```python
print("Treatment_Cost Skewness:", df['Treatment_Cost'].skew())

median_cost = df['Treatment_Cost'].median()
df['Treatment_Cost'] = df['Treatment_Cost'].fillna(median_cost)

print("Missing values in Treatment_Cost after imputation:", df['Treatment_Cost'].isnull().sum())
```

---
---

### Q4. Duplicate Patient Records — Scenario: Some patient records were entered multiple times. Task: Identify duplicate rows. Remove duplicates. Compare dataset size before and after.

-->  

Answer:  
A total of 99 fully duplicated rows (where every column value is identical) were found in the dataset out of 5,100 total records. After removing these duplicates, the dataset size reduces from 5,100 rows to 5,001 rows.

It's worth noting that 1,215 rows share a repeated Patient_ID, but these are not necessarily true duplicates — they likely represent the same patient visiting the hospital multiple times with different details (different diagnosis, cost, or date). Only rows that are fully identical across every column are treated as duplicate data-entry errors and removed.

```python
duplicate_rows = df[df.duplicated()]
print("Number of duplicate rows:", duplicate_rows.shape[0])

print("Dataset size before removing duplicates:", df.shape)

df = df.drop_duplicates()

print("Dataset size after removing duplicates:", df.shape)
```

---
---

### Q5. Invalid Age Values (Data Quality Check) — Scenario: Some patients have unrealistic age values (e.g., >100 or <0). Task: Detect such records. Decide whether to remove or correct them.

-->  

Answer:  
After checking the Age column, the values range from a minimum of 0 to a maximum of 99, with no records found below 0 or above 100. So in this particular dataset, there are currently no unrealistic Age values present.

Even though no invalid records were found, the detection step is still important as a data quality check, since such values could appear in future data. If unrealistic ages did exist, the correct approach would be to remove them rather than attempt to "correct" them, since a negative age or an age of 150 cannot be reliably fixed without additional context, and keeping such records would distort any medical analysis.

```python
invalid_age = df[(df['Age'] < 0) | (df['Age'] > 100)]
print("Number of invalid age records:", invalid_age.shape[0])
print(invalid_age[['Patient_ID', 'Age']])

df = df[(df['Age'] >= 0) & (df['Age'] <= 100)]
print("Dataset shape after removing invalid age rows:", df.shape)
```

---
---

### Q6. Outlier Detection (Treatment Cost) — Scenario: Extreme treatment costs are affecting analysis. Task: Detect outliers using IQR method. Display number of outliers.

-->  

Answer:  
Using the IQR method on Treatment_Cost: Q1 = ₹12,498, Q3 = ₹37,922, and IQR = ₹25,424. This gives an upper bound of ₹76,058 (the lower bound is negative and therefore not practically restrictive). Any treatment cost above ₹76,058 is flagged as a statistical outlier.

A total of 50 outlier records were detected using this method. These likely correspond to unusually expensive treatments, such as major surgeries or extended hospital stays, and could distort average cost calculations if not handled or analyzed separately.

```python
Q1 = df['Treatment_Cost'].quantile(0.25)
Q3 = df['Treatment_Cost'].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("Q1:", Q1, "Q3:", Q3, "IQR:", IQR)
print("Lower Bound:", lower_bound, "Upper Bound:", upper_bound)

outliers = df[(df['Treatment_Cost'] < lower_bound) | (df['Treatment_Cost'] > upper_bound)]
print("Number of outliers in Treatment_Cost:", outliers.shape[0])
```

---
---

### Q7. Outlier Treatment — Scenario: The business team wants to retain all records. Task: Apply capping (Winsorization) on Treatment_Cost. Use 5th and 95th percentile.

-->  

Answer:  
Since the business team wants to retain all records (rather than deleting outliers as in Q6), Winsorization (capping) is used instead. This method does not remove any rows — it simply limits extreme values to a defined boundary.

The 5th percentile of Treatment_Cost is ₹2,914.6 and the 95th percentile is ₹48,188.1. Any value below ₹2,914.6 is capped up to that value, and any value above ₹48,188.1 is capped down to that value. After applying this, 452 values were capped. The maximum cost dropped from ₹199,703 to ₹48,188.1, and the standard deviation reduced significantly (from ≈23,225 to ≈14,352), meaning the data is now less spread out while every original row is still retained.

```python
p5 = df['Treatment_Cost'].quantile(0.05)
p95 = df['Treatment_Cost'].quantile(0.95)
print("5th percentile:", p5)
print("95th percentile:", p95)

df['Treatment_Cost_Capped'] = df['Treatment_Cost'].clip(lower=p5, upper=p95)

print("Before capping:\n", df['Treatment_Cost'].describe())
print("\nAfter capping:\n", df['Treatment_Cost_Capped'].describe())
```

---
---

### Q8. Transformation — Scenario: Treatment cost is highly skewed. Task: Apply log transformation. Create a new column. Compare before vs after distribution.

-->  

Answer:  
Treatment_Cost has a high right-skew of approximately 4.49, meaning a few very expensive treatments pull the distribution's tail far to the right. A log transformation compresses large values much more than small values, which pulls in that long tail and makes the distribution closer to normal.

Using `np.log1p()` (log(1+x), chosen to safely handle any zero values), a new column `Treatment_Cost_Log` is created. After transformation, the skewness drops from 4.49 to approximately -1.11 — a dramatic reduction in skew, much closer to a symmetric distribution. This makes the data more suitable for models and statistical tests that assume normality.

```python
import numpy as np

df['Treatment_Cost_Log'] = np.log1p(df['Treatment_Cost'])

print("Original Skewness:", df['Treatment_Cost'].skew())
print("Log-Transformed Skewness:", df['Treatment_Cost_Log'].skew())

print("\nBefore (original):\n", df['Treatment_Cost'].describe())
print("\nAfter (log-transformed):\n", df['Treatment_Cost_Log'].describe())
```

---
---

### Q9. Time-Based Missing Handling — Scenario: Admission dates should follow a logical sequence. Task: Sort data by Admission_Date. Apply forward fill or backward fill where appropriate. Justify your choice.

-->  

Answer:  
Checking the Admission_Date column shows it actually has zero missing values in this dataset, so no values technically need to be filled here. However, the required methodology is still demonstrated below as good practice, since this approach would be essential if missing dates were present.

The data is first sorted chronologically by Admission_Date so any fill method respects the logical time sequence. Forward fill (`ffill`) is the justified choice over backward fill, because in time-based hospital records, it is more realistic to assume a missing admission date is close to the previous (most recent past) entry rather than borrowing a future date that hasn't occurred yet from the patient's perspective. Backward fill could incorrectly imply a record existed before it was actually created.

```python
df['Admission_Date'] = pd.to_datetime(df['Admission_Date'])

df = df.sort_values(by='Admission_Date')

print("Missing values in Admission_Date before fill:", df['Admission_Date'].isnull().sum())

df['Admission_Date'] = df['Admission_Date'].fillna(method='ffill')

print("Missing values in Admission_Date after fill:", df['Admission_Date'].isnull().sum())
```

---
---
"""